services:
  frontend:
    image: ghcr.io/rgss-cs/williams-rgss-website-dev-frontend-frontend:latest
    container_name: williams-rgss-frontend
    restart: unless-stopped

    ports:
      - "3000:3000"

    environment:
      NODE_ENV: production
      BACKEND_URL: http://backend:8000

    pull_policy: always

    networks: 
      - internetwork


networks:
  internetwork:
    driver: bridge